language: node_js
node_js:
  - 'node'

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run lint
  - npm run test:unit
  - npm run build
  - npm install netlify-cli -g

deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=dist --prod
  on:
    branch: master
